///NASIONAL////

#EXTINF:-1 tvg-id="RCTI.id" tvg-logo="https://static.mncnow.id/images/channel/928ba7e3/38c2.png" group-title="NASIONAL",  RCTI HD



$http://syarman.xyz/NATIONAL/RCTI.m3u8

#EXTINF:-1 tvg-id="GTV.id" tvg-logo="https://static.mncnow.id/images/channel/ef3eed68/040d.png" group-title="NASIONAL", GTV HD



$http://syarman.xyz/NATIONAL/GTV.m3u8

#EXTINF:-1 tvg-id="MNCTV.id" tvg-logo="https://static.mncnow.id/images/channel/99cf87f4/d2c2.png" group-title="NASIONAL",  MNCTV HD

http://syarman.xyz/NATIONAL/MNCTV.m3u8

#EXTINF:-1 tvg-id="INEWS.id" tvg-logo="https://static.mncnow.id/images/channel/182d1c3d/c6f1.png" group-title="NASIONAL",  INEWS HD

http://syarman.xyz/NATIONAL/INEWS.m3u8

#EXTINF:-1 tvg-id="ANTV.id" tvg-logo="https://i.postimg.cc/85gfZ13X/antv.png" group-title=" NASIONAL", ANTV
http://playlist.urfan.web.id/qwr9ew/s/s07/01.m3u8

#EXTINF:-1 tvg-id="daaitv.id" tvg-logo="https://i.postimg.cc/761GcFrH/daai-tv.png" group-title=" NASIONAL", DAAI TV
http://playlist.urfan.web.id/qwr9ew/s/s13/01.m3u8

#EXTINF:-1 tvg-id="INDOSIAR.id" tvg-id="indosiar" tvg-logo="https://i.postimg.cc/N0SkBqnR/indosiar.png" group-title=" NASIONAL", INDOSIAR


http://playlist.urfan.web.id/qwr9ew/s/s04/01.m3u8

#EXTINF:-1 tvg-id="KOMPASTV.id" tvg-id="kompastv" tvg-logo="https://i.postimg.cc/4yb66Kx1/kompas-tv.png" group-title=" NASIONAL", KOMPAS TV 
http://playlist.urfan.web.id/qwr9ew/s/s104/01.m3u8

#EXTINF:-1 tvg-id="MetroTV.id" tvg-id="metrotv" tvg-logo="https://i.postimg.cc/MK50Xj46/metro-tv.png" group-title=" NASIONAL", METRO TV
http://playlist.urfan.web.id/uq2663/h/h12/01.m3u8


#EXTINF:-1 tvg-id="NET.id" tvg-logo="https://i.postimg.cc/sX57zB7R/net.png" group-title=" NASIONAL", NET TV HD
http://playlist.urfan.web.id/qwr9ew/s/s08/01.m3u8

#EXTINF:-1 tvg-id="Rajawali.id" tvg-logo="https://i.postimg.cc/TYtmTvLh/rtv.png" group-title=" NASIONAL", RTV
http://playlist.urfan.web.id/dr9445/h/h10/02.m3u8


#EXTINF:-1 tvg-id="SCTV.id" tvg-logo="https://i.postimg.cc/xjyMFz9v/sctv.png" group-title=" NASIONAL", SCTV
http://playlist.urfan.web.id/qwr9ew/s/s03/01.m3u8

#EXTINF:-1 tvg-id="TRANSTV.id" tvg-id="transtv" tvg-logo="https://i.postimg.cc/BntF67Hp/trans-tv.png" group-title=" NASIONAL", TRANS TV
https://video.detik.com/transtv/smil:transtv.smil/chunklist_w1372215912_b744100_sleng.m3u8

#EXTINF:-1 tvg-id="TRANS7.id" tvg-id="trans7" tvg-logo="https://i.postimg.cc/BQSHWnvd/trans-7.png" group-title=" NASIONAL", TRANS 7 
https://video.detik.com/trans7/smil:trans7.smil/chunklist_w1304503729_b744100_sleng.m3u8

#EXTINF:-1 tvg-id="TVOne.id" tvg-logo="https://i.postimg.cc/3x6vDjZT/tv-one.png" group-title=" NASIONAL", TV ONE 
http://playlist.urfan.web.id/qwr9ew/s/s105/01.m3u8


#EXTINF:-1 tvg-id="TVRINasional.id" tvg-logo="https://i.postimg.cc/GpysPBMs/tvri.png" group-title=" NASIONAL", TVRI
http://118.97.50.107/Content/HLS/Live/Channel(TVRINASIONAL)/index.m3u8


#EXTINF:-1 tvg-id="Ochannel.id" tvg-logo="https://thumbor.prod.vid.id/Oi4K0Zef5RaOK9DF2_eiiYDtOtE=/230x230/filters:quality(70)/vidio-web-prod-livestreaming/uploads/livestreaming/square_image/206/67385c.png" group-title="NASIONAL", O Channel
https://dukun.masuk.id/lokal/ochannel1.m3u8
